source 'https://rubygems.org'
gem 'activerecord', require: 'active_record'
gem 'activerecord-import'
gem 'activesupport', require: 'active_support/all'
gem 'addressable', require: 'addressable/uri'
gem 'json'
gem 'natto'
gem 'nokogiri'
gem 'sqlite3'
gem 'squeel'
gem 'tweetstream'
gem 'twitter'
gem 'clockwork'
gem 'rubocop'
