default: &default
  consumer_key: <%= ENV['TW_CONSUMER_KEY'] %>
  consumer_secret:  <%= ENV['TW_CONSUMER_SECRET'] %>
  access_token:  <%= ENV['TW_ACCESS_TOKEN'] %>
  access_token_secret: <%= ENV['TW_ACCESS_TOKEN_SECRET'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
